id: P4A6D65CA
initial_creation_type: ocr
source_metadata:
  volumes:
    75a367e522c74c2caeb098fe40e45e3e:
      base_file: v062.txt
      image_group_id: I1PD95907
      title: དེ་ཁོ་ན་ཉིད་སྣང་བ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1557
      volume_number: 62
